config/routes.rb
Americanparts::Application.routes.draw do
  scope "(:locale)", :locale => /en|es/ do
    root :to => 'store#home'
    get :send_promotion_mail, to: 'products#send_promotion_mail', as: :send_promotion_mail
    post :send_promotion_mail, to: 'products#send_promotion_mail', as: :send_promotion_mail
    get "products/promotion"
    resources :products
    devise_for :users
    resources :line_items
    resources :carts
    resources :orders
    resources :users
    get "store/index"
    get "store/home"
    get "store/terms"
    get "store/contact"
    get "store/products"
    get "store/productslist"
    get "store/payinfo"
    get "store/orderstatus"
    
  end

  
  resources :line_items do
    put 'erase', on: :member
  end

end

app/views/layouts/_menu.html.erb
<nav>
	<ul class="dropable">
	<li class="drop"><%= link_to t('.HOME'), store_home_path, :class => "topmenu" %></li>
	<li class="drop"><%= link_to t('.STORE'), store_index_path, :class =>  "topmenu" %></li>
	<li class="drop"><%= link_to t('.CONTACT'), store_contact_path, :class =>  "topmenu" %></li>
	<% if user_signed_in? and current_user.common == true %>
	<li class="drop"><%= link_to 'ADMIN', store_home_path, :class =>  "topmenu" %>
		<div class="dropdownContain">
				<div class="dropOut">
					<div class="triangle"></div>
					<ul>
				  		<li>
						<%= link_to "PRODUCTS", new_product_path ,:class => "secondmenu" %>
						<%= link_to "USERS", users_path ,:class => "secondmenu" %>
						<%= link_to "ORDERS", orders_path ,:class => "secondmenu" %>
						<%= link_to "PROMOTION", products_promotion_path ,:class => "secondmenu" %>
				  		</li>
					</ul>
				</div>
			</div>
	</li>

	<% end %>
			<% @marcas.each do |producto| %>
		<li class="drop">
			<%= link_to producto.marc.upcase, store_productslist_path(:marca => producto.marc,locale: I18n.locale), :class => "topmenu" %>
			<div class="dropdownContain">
				<div class="dropOut">
					<div class="triangle"></div>
					<ul>
					<% if "#{producto.marc}" == 'Copeland' %>
			  		<% @Busqueda = @productoCop %>
			  		<% elsif "#{producto.marc}" == 'Carrier' %>
			  		<% @Busqueda = @productoCarr %>
			  		<% elsif "#{producto.marc}" == 'Bitzer' %>
			  		<% @Busqueda = @productoBit %>
			  		<% elsif "#{producto.marc}" == 'Trane' %>
			  		<% @Busqueda = @productoTra %>
			  		<% elsif "#{producto.marc}" == 'York' %>
			  		<% @Busqueda = @productoYork %>
			  		<% end %>
			  		<% @Busqueda.each do |producto1| %>
			  		<li>
			  		<% @name = "#{producto1.names.downcase.capitalize}" %>	
			  		<% @marca = "#{producto.marc}" %>	
					<%= link_to @name, store_products_path(:marca => @marca, :name => @name ) ,:class => "secondmenu" %>
			  			</li>
	  				<% end %>
					</ul>
				</div>
			</div>
		</li>
		<% end %>
		
		<!-- <li class="drop">
				<a href="#" class="link">You</a>
				<div class="dropdownContain">
					<div class="dropOut">
						<div class="triangle"></div>
						<ul>
							<li>Plan</li>
							<li>Account Settings</li>
							<li>Switch Account</li>
							<li>Sign Out</li>
						</ul>
					</div>
				</div>
			
		</li> -->
		</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>USA Compressor Parts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body class="<%= controller.controller_name %>" id = "body">
<div id="contenido">
	<!--here goes logging and language info-->
		<div id="loginImg">
			<%= image_tag("logo/logo_2.jpg",class: 'logo')%>
		</div>

		<!--here goes all login partial template-->
		<div id="loginLogin">
			<p>
			<span style ="padding-left:15px;">
			<% if user_signed_in? %>
			  <%= t('.text1') %> <strong> <%= current_user.username %> </strong>|
			  <%= link_to t('.linkLoggin'), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		&nbsp&nbsp&nbsp <i class="fa fa-user" style="font-size:1.25em;"></i> 
		<%= link_to t('.edit'), edit_user_registration_path, :class => 'navbar-link'  %>
		&nbsp&nbsp&nbsp <i class="fa fa-cubes" style="font-size:1.25em;"></i>
		<%= link_to t('.Orders'), store_orderstatus_path, :class => 'navbar-link'  %>
			<% else %>
			<%= link_to t('.linkCreate'), new_user_registration_path, :class => 'navbar-link'  %>
			<% end %>
			<span style ="float:right;padding-right:70px;">
			<i class="fa fa-globe" style="font-size:1.7em;"></i>	&nbsp
			<%= link_to_unless I18n.locale == :en, "EN", locale: :en %>&nbsp
			<%= link_to_unless I18n.locale == :es, "ES", locale: :es %>
			</span>
			</p>
			<%= render 'devise/sessions/partialnew' %>
		</div>
	<!--here sup menu to add deployed menu-->
	<div id="navegacion">
		<%= render 'layouts/menu' %>
	</div>
	<!-- heres goes all main body of the web page -->
	<div id="side_l" style="color:white">
		xleft
	</div>
	<!--Aquí la parte cuerpo de la pag-->
	<div id="main">	
		<!-- 		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p> -->
		<%= yield %>
	</div>
	<div id="side_r">
		<div id="cart">
			<%= render @cart %>
		</div>
		<%= image_tag("compressors/Bitzer2.jpg",class: 'comp1')%>
		<%= image_tag("compressors/Carrier.jpg",class: 'comp1')%> <br>
		<%= image_tag("compressors/Copeland.jpg",class: 'comp1')%>
		<%= image_tag("compressors/Bitzer2.jpg",class: 'comp1')%>
	</div>
</div>
</body>
</html>